import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from "./components/Footer/footer.js";
import Header from "./components/Header/header.js"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | NDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Header />
      </main>
    <Footer/>
    </div>
  )
}
