import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Admin.module.css'
import Footer from "./components/Footer/footer.js";
import Header from "./components/Header/header.js"
import { Icon, Table, Button, Input, Dropdown } from 'semantic-ui-react'
import { useState } from 'react';
import React from "react"
import ActiveLink from './components/ActiveLink';

export default function Volumes() {
    const [render, setRender] = useState(false);
    getLoginInfo().then(data => {
        if (!data.error) {
            setRender(true);
        }
    })
    return (
        <div>
            <Head>
                <title>Jobs | NDS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <main>
                <Header />
                <div className='main'>
                    <Body render={render} />
                </div>
            </main>
            <Footer />
        </div>
    )
}
function Body(props) {
    if (!props.render) return (<h2 style={{ color: "red" }}>Authentication Required!</h2>)
    return (
        <div>
            <h1>Background Jobs</h1>
            <List />
        </div>
    )
}
function List() {
    const [jobs, setJobs] = useState([{
        name: <Icon loading name="circle notched" />,
        runs_every: <Icon loading name="circle notched" />,
        enabled: <Icon loading name="circle notched" />,
        actions: [],
        loading: true
    }]);
    if (jobs[0] && jobs[0].loading) {
        getJobs().then(data => {
            setJobs(data)
        })
    }
    return (
        <div>
            <Table celled striped>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>Name</Table.HeaderCell>
                        <Table.HeaderCell>Runs every</Table.HeaderCell>
                        <Table.HeaderCell>Enabled</Table.HeaderCell>
                        <Table.HeaderCell>Actions</Table.HeaderCell>
                        <Table.HeaderCell></Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    {
                        jobs.map((job, key) => {
                            var actionText = ""
                            console.log(job)
                            job.actions.forEach(action => {
                                actionText += action.action + ", "
                            })
                            if (job.actions.length > 0) actionText = actionText.slice(0, -2)
                            return (
                                <Table.Row key={key}>
                                    <Table.Cell>{job.name}</Table.Cell>
                                    <Table.Cell>{job.run_every} minutes</Table.Cell>
                                    <Table.Cell>{job.enabled.toString()}</Table.Cell>
                                    <Table.Cell>{actionText}</Table.Cell>
                                    <Table.Cell style={{fontSize: "15px"}}>
                                        <a style={{ cursor: "pointer" }} onClick={async () => {
                                            if (!confirm("Are you sure you want to delete this job? This action cannot be undone.")) return;
                                            let results = await fetch(`/api/jobs?auth=${getCachedAuth()}&action=deleteJob&id=${job.id}`);
                                            results = await results.json();
                                            alert(results.data || results.error);
                                            setJobs(await getJobs())
                                        }}><Icon name='trash alternate outline' /></a>
                                        <ActiveLink href={"/jobs/"+job.id}>
                                            <Icon name="edit" style={{marginLeft: "10px"}}/>
                                        </ActiveLink>
                                    </Table.Cell>
                                </Table.Row>
                            )
                        })
                    }
                </Table.Body>
            </Table>
            <Button primary onClick={async () => {
                let name = prompt("Enter a name for the job you want to create");
                if (!name) return;
                let results = await fetch(`/api/jobs?auth=${getCachedAuth()}&action=createJob&name=${name}`);
                results = await results.json();
                alert(results.data || results.error);
                setJobs(await getJobs())
            }}>New Job</Button>
        </div>
    )
}

async function getVolumes() {
    const res = await fetch(`/api/volumes?auth=${getCachedAuth()}&action=listVolumes`);
    const data = await res.json()
    let volumes = data.data;
    let deployments = await getDeployments()
    for (let i in volumes) {
        for (let p in deployments) {
            if (deployments[p].volumes.find(x => {
                if (!volumes[i].DockerInfo) return false;
                else return x.id === volumes[i].DockerInfo.Name.slice("nds-config-".length)
            })) {
                volumes[i].attachedDeployment = deployments[p].name
            } else {
                volumes[i].attachedDeployment = "N/A"
            }
        }
    }
    return volumes
    async function getDeployments() {
        const response = await fetch(`/api/deployments?auth=${getCachedAuth()}&action=getDeployments`);
        const data = await response.json();
        return data.data
    }
}
async function getJobs() {
    const res = await fetch(`/api/jobs?auth=${getCachedAuth()}&action=listJobs`);
    const data = await res.json()
    return data.data
}

async function getLoginInfo() {
    const res = await fetch(`/api/user?auth=${getCachedAuth()}`);
    const data = await res.json()
    return data;
}
function getCachedAuth() {
    if (typeof sessionStorage !== "undefined") {
        if (sessionStorage.getItem("auth")) {
            return sessionStorage.getItem("auth")
        } else {
            return localStorage.getItem("auth")
        }
    }
}